### ISSUE TITLE
"alignments" submodule missing URL

### ISSUE THREAD

**Issue by danielhers** [ida-szubert/amr_ud#2]
The scripts `dp1.py` and `dp2.py` try to access `./alignments/amr_ud_alignments_ldc_signatures.txt`, but it doesn't exist. There is a submodule `alignments` but since there is no `.gitmodules` file, I cannot get it, so the directory is empty. Normally I would run `git submodule update --init` to initialize the submodules in the repository, but when I do so I get:
```
fatal: No url found for submodule path 'alignments' in .gitmodules
```

**Comment by nschneid** [comment]
@danielhers is it fixed now?

**Comment by danielhers** [comment]
Looks good, thanks!
